### ISSUE TITLE
Install with Renderman 23 / Blender 2.81

### ISSUE THREAD

**Issue by NicolasSofu** [ian-hsieh/RenderManForBlender#7]
Hello,

i have tried to install the addon with blender 2.80 and 2.81 and i get the following error : 

Exception in module register(): C:\Users\babonf\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\RenderManForBlender-master\__init__.py
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\modules\addon_utils.py", line 384, in enable
    mod.register()
  File "C:\Users\babonf\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\RenderManForBlender-master\__init__.py", line 227, in register
    load_addon()
  File "C:\Users\babonf\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\RenderManForBlender-master\__init__.py", line 189, in load_addon
    if filepath_utils.guess_rmantree():
  File "C:\Users\babonf\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\RenderManForBlender-master\rman_utils\filepath_utils.py", line 92, in guess_rmantree
    rfb_log().debug('Fallback to using RMANTREE.')
  File "C:\Users\babonf\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\RenderManForBlender-master\rfb_logger\__init__.py", line 128, in rfb_log
    check_logfile_preferences()
  File "C:\Users\babonf\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\RenderManForBlender-master\rfb_logger\__init__.py", line 113, in check_logfile_preferences
    rman_prefs = prefs_utils.get_addon_prefs()
  File "C:\Users\babonf\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\RenderManForBlender-master\rman_utils\prefs_utils.py", line 5, in get_addon_prefs
    addon = bpy.context.preferences.addons[RFB_PREFS_NAME]
KeyError: 'bpy_prop_collection[key]: key "RenderManForBlender" not found'

**Comment by ian-hsieh** [comment]
You should rename the folder from RenderManForBlender-master to just RenderManForBlender.

Also, note that the code in this repository is not the latest. All development of the addon has been moved into an internal gitlab repository. When the addon is released, the code will be merged up to the prman-pixar repository.
